// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: tracks/tracks.proto

package tracks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TracksService_TrackInfo_FullMethodName = "/proto.TracksService/TrackInfo"
)

// TracksServiceClient is the client API for TracksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TracksServiceClient interface {
	TrackInfo(ctx context.Context, in *TrackInfoReq, opts ...grpc.CallOption) (*TrackInfoRes, error)
}

type tracksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTracksServiceClient(cc grpc.ClientConnInterface) TracksServiceClient {
	return &tracksServiceClient{cc}
}

func (c *tracksServiceClient) TrackInfo(ctx context.Context, in *TrackInfoReq, opts ...grpc.CallOption) (*TrackInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackInfoRes)
	err := c.cc.Invoke(ctx, TracksService_TrackInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TracksServiceServer is the server API for TracksService service.
// All implementations must embed UnimplementedTracksServiceServer
// for forward compatibility.
type TracksServiceServer interface {
	TrackInfo(context.Context, *TrackInfoReq) (*TrackInfoRes, error)
	mustEmbedUnimplementedTracksServiceServer()
}

// UnimplementedTracksServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTracksServiceServer struct{}

func (UnimplementedTracksServiceServer) TrackInfo(context.Context, *TrackInfoReq) (*TrackInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackInfo not implemented")
}
func (UnimplementedTracksServiceServer) mustEmbedUnimplementedTracksServiceServer() {}
func (UnimplementedTracksServiceServer) testEmbeddedByValue()                       {}

// UnsafeTracksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TracksServiceServer will
// result in compilation errors.
type UnsafeTracksServiceServer interface {
	mustEmbedUnimplementedTracksServiceServer()
}

func RegisterTracksServiceServer(s grpc.ServiceRegistrar, srv TracksServiceServer) {
	// If the following call pancis, it indicates UnimplementedTracksServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TracksService_ServiceDesc, srv)
}

func _TracksService_TrackInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracksServiceServer).TrackInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TracksService_TrackInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracksServiceServer).TrackInfo(ctx, req.(*TrackInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TracksService_ServiceDesc is the grpc.ServiceDesc for TracksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TracksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TracksService",
	HandlerType: (*TracksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrackInfo",
			Handler:    _TracksService_TrackInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracks/tracks.proto",
}
