// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: tracks/tracks.proto

package tracks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         string                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfoReq) Reset() {
	*x = TrackInfoReq{}
	mi := &file_tracks_tracks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfoReq) ProtoMessage() {}

func (x *TrackInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_tracks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfoReq.ProtoReflect.Descriptor instead.
func (*TrackInfoReq) Descriptor() ([]byte, []int) {
	return file_tracks_tracks_proto_rawDescGZIP(), []int{0}
}

func (x *TrackInfoReq) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *TrackInfoReq) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

type TrackInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *TrackInfo             `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfoRes) Reset() {
	*x = TrackInfoRes{}
	mi := &file_tracks_tracks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfoRes) ProtoMessage() {}

func (x *TrackInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_tracks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfoRes.ProtoReflect.Descriptor instead.
func (*TrackInfoRes) Descriptor() ([]byte, []int) {
	return file_tracks_tracks_proto_rawDescGZIP(), []int{1}
}

func (x *TrackInfoRes) GetTrack() *TrackInfo {
	if x != nil {
		return x.Track
	}
	return nil
}

type TrackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Listeners     int32                  `protobuf:"varint,4,opt,name=listeners,proto3" json:"listeners,omitempty"`
	Playcounts    int32                  `protobuf:"varint,5,opt,name=playcounts,proto3" json:"playcounts,omitempty"`
	Genres        []string               `protobuf:"bytes,6,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfo) Reset() {
	*x = TrackInfo{}
	mi := &file_tracks_tracks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfo) ProtoMessage() {}

func (x *TrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_tracks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfo.ProtoReflect.Descriptor instead.
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return file_tracks_tracks_proto_rawDescGZIP(), []int{2}
}

func (x *TrackInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackInfo) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *TrackInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TrackInfo) GetListeners() int32 {
	if x != nil {
		return x.Listeners
	}
	return 0
}

func (x *TrackInfo) GetPlaycounts() int32 {
	if x != nil {
		return x.Playcounts
	}
	return 0
}

func (x *TrackInfo) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

var File_tracks_tracks_proto protoreflect.FileDescriptor

var file_tracks_tracks_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x0c,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x0c, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x22, 0xa9, 0x01, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x32, 0x46,
	0x0a, 0x0d, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x35, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x42, 0x16, 0x5a, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x2d, 0x66,
	0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_tracks_tracks_proto_rawDescOnce sync.Once
	file_tracks_tracks_proto_rawDescData []byte
)

func file_tracks_tracks_proto_rawDescGZIP() []byte {
	file_tracks_tracks_proto_rawDescOnce.Do(func() {
		file_tracks_tracks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracks_tracks_proto_rawDesc), len(file_tracks_tracks_proto_rawDesc)))
	})
	return file_tracks_tracks_proto_rawDescData
}

var file_tracks_tracks_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tracks_tracks_proto_goTypes = []any{
	(*TrackInfoReq)(nil), // 0: proto.TrackInfoReq
	(*TrackInfoRes)(nil), // 1: proto.TrackInfoRes
	(*TrackInfo)(nil),    // 2: proto.TrackInfo
}
var file_tracks_tracks_proto_depIdxs = []int32{
	2, // 0: proto.TrackInfoRes.track:type_name -> proto.TrackInfo
	0, // 1: proto.TracksService.TrackInfo:input_type -> proto.TrackInfoReq
	1, // 2: proto.TracksService.TrackInfo:output_type -> proto.TrackInfoRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tracks_tracks_proto_init() }
func file_tracks_tracks_proto_init() {
	if File_tracks_tracks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracks_tracks_proto_rawDesc), len(file_tracks_tracks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracks_tracks_proto_goTypes,
		DependencyIndexes: file_tracks_tracks_proto_depIdxs,
		MessageInfos:      file_tracks_tracks_proto_msgTypes,
	}.Build()
	File_tracks_tracks_proto = out.File
	file_tracks_tracks_proto_goTypes = nil
	file_tracks_tracks_proto_depIdxs = nil
}
