// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: tracks/tracks.proto

package tracks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        string                 `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Track         string                 `protobuf:"bytes,2,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfoReq) Reset() {
	*x = TrackInfoReq{}
	mi := &file_tracks_tracks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfoReq) ProtoMessage() {}

func (x *TrackInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_tracks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfoReq.ProtoReflect.Descriptor instead.
func (*TrackInfoReq) Descriptor() ([]byte, []int) {
	return file_tracks_tracks_proto_rawDescGZIP(), []int{0}
}

func (x *TrackInfoReq) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *TrackInfoReq) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

type TrackSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         string                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackSearchReq) Reset() {
	*x = TrackSearchReq{}
	mi := &file_tracks_tracks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackSearchReq) ProtoMessage() {}

func (x *TrackSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_tracks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackSearchReq.ProtoReflect.Descriptor instead.
func (*TrackSearchReq) Descriptor() ([]byte, []int) {
	return file_tracks_tracks_proto_rawDescGZIP(), []int{1}
}

func (x *TrackSearchReq) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

func (x *TrackSearchReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TrackSearchReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type TrackInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Listeners     int32                  `protobuf:"varint,4,opt,name=listeners,proto3" json:"listeners,omitempty"`
	Playcounts    int32                  `protobuf:"varint,5,opt,name=playcounts,proto3" json:"playcounts,omitempty"`
	Genres        []string               `protobuf:"bytes,6,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfoRes) Reset() {
	*x = TrackInfoRes{}
	mi := &file_tracks_tracks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfoRes) ProtoMessage() {}

func (x *TrackInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_tracks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfoRes.ProtoReflect.Descriptor instead.
func (*TrackInfoRes) Descriptor() ([]byte, []int) {
	return file_tracks_tracks_proto_rawDescGZIP(), []int{2}
}

func (x *TrackInfoRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackInfoRes) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *TrackInfoRes) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TrackInfoRes) GetListeners() int32 {
	if x != nil {
		return x.Listeners
	}
	return 0
}

func (x *TrackInfoRes) GetPlaycounts() int32 {
	if x != nil {
		return x.Playcounts
	}
	return 0
}

func (x *TrackInfoRes) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type TrackSearchRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Listeners     int32                  `protobuf:"varint,3,opt,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackSearchRes) Reset() {
	*x = TrackSearchRes{}
	mi := &file_tracks_tracks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackSearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackSearchRes) ProtoMessage() {}

func (x *TrackSearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_tracks_tracks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackSearchRes.ProtoReflect.Descriptor instead.
func (*TrackSearchRes) Descriptor() ([]byte, []int) {
	return file_tracks_tracks_proto_rawDescGZIP(), []int{3}
}

func (x *TrackSearchRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackSearchRes) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *TrackSearchRes) GetListeners() int32 {
	if x != nil {
		return x.Listeners
	}
	return 0
}

var File_tracks_tracks_proto protoreflect.FileDescriptor

var file_tracks_tracks_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x0c,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x22, 0x50, 0x0a, 0x0e, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xac, 0x01, 0x0a,
	0x0c, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x22, 0x5a, 0x0a, 0x0e, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x32, 0x83, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x12, 0x3b, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x42, 0x16, 0x5a,
	0x14, 0x6c, 0x61, 0x73, 0x74, 0x2d, 0x66, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_tracks_tracks_proto_rawDescOnce sync.Once
	file_tracks_tracks_proto_rawDescData []byte
)

func file_tracks_tracks_proto_rawDescGZIP() []byte {
	file_tracks_tracks_proto_rawDescOnce.Do(func() {
		file_tracks_tracks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracks_tracks_proto_rawDesc), len(file_tracks_tracks_proto_rawDesc)))
	})
	return file_tracks_tracks_proto_rawDescData
}

var file_tracks_tracks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tracks_tracks_proto_goTypes = []any{
	(*TrackInfoReq)(nil),   // 0: proto.TrackInfoReq
	(*TrackSearchReq)(nil), // 1: proto.TrackSearchReq
	(*TrackInfoRes)(nil),   // 2: proto.TrackInfoRes
	(*TrackSearchRes)(nil), // 3: proto.TrackSearchRes
}
var file_tracks_tracks_proto_depIdxs = []int32{
	0, // 0: proto.TracksService.TrackInfo:input_type -> proto.TrackInfoReq
	1, // 1: proto.TracksService.TrackSearch:input_type -> proto.TrackSearchReq
	2, // 2: proto.TracksService.TrackInfo:output_type -> proto.TrackInfoRes
	3, // 3: proto.TracksService.TrackSearch:output_type -> proto.TrackSearchRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracks_tracks_proto_init() }
func file_tracks_tracks_proto_init() {
	if File_tracks_tracks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracks_tracks_proto_rawDesc), len(file_tracks_tracks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracks_tracks_proto_goTypes,
		DependencyIndexes: file_tracks_tracks_proto_depIdxs,
		MessageInfos:      file_tracks_tracks_proto_msgTypes,
	}.Build()
	File_tracks_tracks_proto = out.File
	file_tracks_tracks_proto_goTypes = nil
	file_tracks_tracks_proto_depIdxs = nil
}
