// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: artists/artists.proto

package artists

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtistsService_ArtistInfo_FullMethodName = "/proto.ArtistsService/ArtistInfo"
)

// ArtistsServiceClient is the client API for ArtistsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtistsServiceClient interface {
	ArtistInfo(ctx context.Context, in *ArtistInfoReq, opts ...grpc.CallOption) (*ArtistInfoRes, error)
}

type artistsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtistsServiceClient(cc grpc.ClientConnInterface) ArtistsServiceClient {
	return &artistsServiceClient{cc}
}

func (c *artistsServiceClient) ArtistInfo(ctx context.Context, in *ArtistInfoReq, opts ...grpc.CallOption) (*ArtistInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtistInfoRes)
	err := c.cc.Invoke(ctx, ArtistsService_ArtistInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtistsServiceServer is the server API for ArtistsService service.
// All implementations must embed UnimplementedArtistsServiceServer
// for forward compatibility.
type ArtistsServiceServer interface {
	ArtistInfo(context.Context, *ArtistInfoReq) (*ArtistInfoRes, error)
	mustEmbedUnimplementedArtistsServiceServer()
}

// UnimplementedArtistsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtistsServiceServer struct{}

func (UnimplementedArtistsServiceServer) ArtistInfo(context.Context, *ArtistInfoReq) (*ArtistInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArtistInfo not implemented")
}
func (UnimplementedArtistsServiceServer) mustEmbedUnimplementedArtistsServiceServer() {}
func (UnimplementedArtistsServiceServer) testEmbeddedByValue()                        {}

// UnsafeArtistsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtistsServiceServer will
// result in compilation errors.
type UnsafeArtistsServiceServer interface {
	mustEmbedUnimplementedArtistsServiceServer()
}

func RegisterArtistsServiceServer(s grpc.ServiceRegistrar, srv ArtistsServiceServer) {
	// If the following call pancis, it indicates UnimplementedArtistsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtistsService_ServiceDesc, srv)
}

func _ArtistsService_ArtistInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtistInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistsServiceServer).ArtistInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtistsService_ArtistInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistsServiceServer).ArtistInfo(ctx, req.(*ArtistInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtistsService_ServiceDesc is the grpc.ServiceDesc for ArtistsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtistsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ArtistsService",
	HandlerType: (*ArtistsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ArtistInfo",
			Handler:    _ArtistsService_ArtistInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "artists/artists.proto",
}
