// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: artists/artists.proto

package artists

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtistInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistInfoReq) Reset() {
	*x = ArtistInfoReq{}
	mi := &file_artists_artists_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistInfoReq) ProtoMessage() {}

func (x *ArtistInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_artists_artists_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistInfoReq.ProtoReflect.Descriptor instead.
func (*ArtistInfoReq) Descriptor() ([]byte, []int) {
	return file_artists_artists_proto_rawDescGZIP(), []int{0}
}

func (x *ArtistInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArtistInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *ArtistInfo            `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistInfoRes) Reset() {
	*x = ArtistInfoRes{}
	mi := &file_artists_artists_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistInfoRes) ProtoMessage() {}

func (x *ArtistInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_artists_artists_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistInfoRes.ProtoReflect.Descriptor instead.
func (*ArtistInfoRes) Descriptor() ([]byte, []int) {
	return file_artists_artists_proto_rawDescGZIP(), []int{1}
}

func (x *ArtistInfoRes) GetArtist() *ArtistInfo {
	if x != nil {
		return x.Artist
	}
	return nil
}

type ArtistInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Listeners     int32                  `protobuf:"varint,2,opt,name=listeners,proto3" json:"listeners,omitempty"`
	Playcounts    int32                  `protobuf:"varint,3,opt,name=playcounts,proto3" json:"playcounts,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistInfo) Reset() {
	*x = ArtistInfo{}
	mi := &file_artists_artists_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistInfo) ProtoMessage() {}

func (x *ArtistInfo) ProtoReflect() protoreflect.Message {
	mi := &file_artists_artists_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistInfo.ProtoReflect.Descriptor instead.
func (*ArtistInfo) Descriptor() ([]byte, []int) {
	return file_artists_artists_proto_rawDescGZIP(), []int{2}
}

func (x *ArtistInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtistInfo) GetListeners() int32 {
	if x != nil {
		return x.Listeners
	}
	return 0
}

func (x *ArtistInfo) GetPlaycounts() int32 {
	if x != nil {
		return x.Playcounts
	}
	return 0
}

func (x *ArtistInfo) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

var File_artists_artists_proto protoreflect.FileDescriptor

var file_artists_artists_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23,
	0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22,
	0x76, 0x0a, 0x0a, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x32, 0x4a, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x42, 0x17, 0x5a, 0x15, 0x6c, 0x61, 0x73, 0x74, 0x2d, 0x66, 0x6d, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_artists_artists_proto_rawDescOnce sync.Once
	file_artists_artists_proto_rawDescData []byte
)

func file_artists_artists_proto_rawDescGZIP() []byte {
	file_artists_artists_proto_rawDescOnce.Do(func() {
		file_artists_artists_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artists_artists_proto_rawDesc), len(file_artists_artists_proto_rawDesc)))
	})
	return file_artists_artists_proto_rawDescData
}

var file_artists_artists_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_artists_artists_proto_goTypes = []any{
	(*ArtistInfoReq)(nil), // 0: proto.ArtistInfoReq
	(*ArtistInfoRes)(nil), // 1: proto.ArtistInfoRes
	(*ArtistInfo)(nil),    // 2: proto.ArtistInfo
}
var file_artists_artists_proto_depIdxs = []int32{
	2, // 0: proto.ArtistInfoRes.artist:type_name -> proto.ArtistInfo
	0, // 1: proto.ArtistsService.ArtistInfo:input_type -> proto.ArtistInfoReq
	1, // 2: proto.ArtistsService.ArtistInfo:output_type -> proto.ArtistInfoRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_artists_artists_proto_init() }
func file_artists_artists_proto_init() {
	if File_artists_artists_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artists_artists_proto_rawDesc), len(file_artists_artists_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artists_artists_proto_goTypes,
		DependencyIndexes: file_artists_artists_proto_depIdxs,
		MessageInfos:      file_artists_artists_proto_msgTypes,
	}.Build()
	File_artists_artists_proto = out.File
	file_artists_artists_proto_goTypes = nil
	file_artists_artists_proto_depIdxs = nil
}
