// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: albums/albums.proto

package albums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlbumInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         string                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumInfoReq) Reset() {
	*x = AlbumInfoReq{}
	mi := &file_albums_albums_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumInfoReq) ProtoMessage() {}

func (x *AlbumInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_albums_albums_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumInfoReq.ProtoReflect.Descriptor instead.
func (*AlbumInfoReq) Descriptor() ([]byte, []int) {
	return file_albums_albums_proto_rawDescGZIP(), []int{0}
}

func (x *AlbumInfoReq) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *AlbumInfoReq) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

type AlbumInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *AlbumInfo             `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumInfoRes) Reset() {
	*x = AlbumInfoRes{}
	mi := &file_albums_albums_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumInfoRes) ProtoMessage() {}

func (x *AlbumInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_albums_albums_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumInfoRes.ProtoReflect.Descriptor instead.
func (*AlbumInfoRes) Descriptor() ([]byte, []int) {
	return file_albums_albums_proto_rawDescGZIP(), []int{1}
}

func (x *AlbumInfoRes) GetAlbum() *AlbumInfo {
	if x != nil {
		return x.Album
	}
	return nil
}

type AlbumInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Listeners     int32                  `protobuf:"varint,3,opt,name=listeners,proto3" json:"listeners,omitempty"`
	Playcounts    int32                  `protobuf:"varint,4,opt,name=playcounts,proto3" json:"playcounts,omitempty"`
	Genres        []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	Tracks        []*AlbumTrackInfo      `protobuf:"bytes,6,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumInfo) Reset() {
	*x = AlbumInfo{}
	mi := &file_albums_albums_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumInfo) ProtoMessage() {}

func (x *AlbumInfo) ProtoReflect() protoreflect.Message {
	mi := &file_albums_albums_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumInfo.ProtoReflect.Descriptor instead.
func (*AlbumInfo) Descriptor() ([]byte, []int) {
	return file_albums_albums_proto_rawDescGZIP(), []int{2}
}

func (x *AlbumInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlbumInfo) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *AlbumInfo) GetListeners() int32 {
	if x != nil {
		return x.Listeners
	}
	return 0
}

func (x *AlbumInfo) GetPlaycounts() int32 {
	if x != nil {
		return x.Playcounts
	}
	return 0
}

func (x *AlbumInfo) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *AlbumInfo) GetTracks() []*AlbumTrackInfo {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type AlbumTrackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumTrackInfo) Reset() {
	*x = AlbumTrackInfo{}
	mi := &file_albums_albums_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumTrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumTrackInfo) ProtoMessage() {}

func (x *AlbumTrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_albums_albums_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumTrackInfo.ProtoReflect.Descriptor instead.
func (*AlbumTrackInfo) Descriptor() ([]byte, []int) {
	return file_albums_albums_proto_rawDescGZIP(), []int{3}
}

func (x *AlbumTrackInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlbumTrackInfo) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *AlbumTrackInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_albums_albums_proto protoreflect.FileDescriptor

var file_albums_albums_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x0c,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x0c, 0x41, 0x6c,
	0x62, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x61, 0x6c,
	0x62, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x22, 0xbc, 0x01, 0x0a, 0x09, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x73, 0x22, 0x58, 0x0a, 0x0e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x46, 0x0a, 0x0d, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x09,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x42, 0x16, 0x5a, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x2d, 0x66, 0x6d, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_albums_albums_proto_rawDescOnce sync.Once
	file_albums_albums_proto_rawDescData []byte
)

func file_albums_albums_proto_rawDescGZIP() []byte {
	file_albums_albums_proto_rawDescOnce.Do(func() {
		file_albums_albums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_albums_albums_proto_rawDesc), len(file_albums_albums_proto_rawDesc)))
	})
	return file_albums_albums_proto_rawDescData
}

var file_albums_albums_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_albums_albums_proto_goTypes = []any{
	(*AlbumInfoReq)(nil),   // 0: proto.AlbumInfoReq
	(*AlbumInfoRes)(nil),   // 1: proto.AlbumInfoRes
	(*AlbumInfo)(nil),      // 2: proto.AlbumInfo
	(*AlbumTrackInfo)(nil), // 3: proto.AlbumTrackInfo
}
var file_albums_albums_proto_depIdxs = []int32{
	2, // 0: proto.AlbumInfoRes.album:type_name -> proto.AlbumInfo
	3, // 1: proto.AlbumInfo.tracks:type_name -> proto.AlbumTrackInfo
	0, // 2: proto.AlbumsService.AlbumInfo:input_type -> proto.AlbumInfoReq
	1, // 3: proto.AlbumsService.AlbumInfo:output_type -> proto.AlbumInfoRes
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_albums_albums_proto_init() }
func file_albums_albums_proto_init() {
	if File_albums_albums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_albums_albums_proto_rawDesc), len(file_albums_albums_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_albums_albums_proto_goTypes,
		DependencyIndexes: file_albums_albums_proto_depIdxs,
		MessageInfos:      file_albums_albums_proto_msgTypes,
	}.Build()
	File_albums_albums_proto = out.File
	file_albums_albums_proto_goTypes = nil
	file_albums_albums_proto_depIdxs = nil
}
