// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: albums/albums.proto

package albums

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlbumsService_AlbumInfo_FullMethodName   = "/proto.AlbumsService/AlbumInfo"
	AlbumsService_AlbumSearch_FullMethodName = "/proto.AlbumsService/AlbumSearch"
)

// AlbumsServiceClient is the client API for AlbumsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlbumsServiceClient interface {
	AlbumInfo(ctx context.Context, in *AlbumInfoReq, opts ...grpc.CallOption) (*AlbumInfoRes, error)
	AlbumSearch(ctx context.Context, in *AlbumSearchReq, opts ...grpc.CallOption) (*AlbumSearchRes, error)
}

type albumsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlbumsServiceClient(cc grpc.ClientConnInterface) AlbumsServiceClient {
	return &albumsServiceClient{cc}
}

func (c *albumsServiceClient) AlbumInfo(ctx context.Context, in *AlbumInfoReq, opts ...grpc.CallOption) (*AlbumInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlbumInfoRes)
	err := c.cc.Invoke(ctx, AlbumsService_AlbumInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) AlbumSearch(ctx context.Context, in *AlbumSearchReq, opts ...grpc.CallOption) (*AlbumSearchRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlbumSearchRes)
	err := c.cc.Invoke(ctx, AlbumsService_AlbumSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlbumsServiceServer is the server API for AlbumsService service.
// All implementations must embed UnimplementedAlbumsServiceServer
// for forward compatibility.
type AlbumsServiceServer interface {
	AlbumInfo(context.Context, *AlbumInfoReq) (*AlbumInfoRes, error)
	AlbumSearch(context.Context, *AlbumSearchReq) (*AlbumSearchRes, error)
	mustEmbedUnimplementedAlbumsServiceServer()
}

// UnimplementedAlbumsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlbumsServiceServer struct{}

func (UnimplementedAlbumsServiceServer) AlbumInfo(context.Context, *AlbumInfoReq) (*AlbumInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlbumInfo not implemented")
}
func (UnimplementedAlbumsServiceServer) AlbumSearch(context.Context, *AlbumSearchReq) (*AlbumSearchRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlbumSearch not implemented")
}
func (UnimplementedAlbumsServiceServer) mustEmbedUnimplementedAlbumsServiceServer() {}
func (UnimplementedAlbumsServiceServer) testEmbeddedByValue()                       {}

// UnsafeAlbumsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlbumsServiceServer will
// result in compilation errors.
type UnsafeAlbumsServiceServer interface {
	mustEmbedUnimplementedAlbumsServiceServer()
}

func RegisterAlbumsServiceServer(s grpc.ServiceRegistrar, srv AlbumsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlbumsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlbumsService_ServiceDesc, srv)
}

func _AlbumsService_AlbumInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlbumInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).AlbumInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumsService_AlbumInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).AlbumInfo(ctx, req.(*AlbumInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_AlbumSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlbumSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).AlbumSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumsService_AlbumSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).AlbumSearch(ctx, req.(*AlbumSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AlbumsService_ServiceDesc is the grpc.ServiceDesc for AlbumsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlbumsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AlbumsService",
	HandlerType: (*AlbumsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AlbumInfo",
			Handler:    _AlbumsService_AlbumInfo_Handler,
		},
		{
			MethodName: "AlbumSearch",
			Handler:    _AlbumsService_AlbumSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "albums/albums.proto",
}
